[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
eframe.workspace = true
protocol = { path = "/home/zakke/ProgStuff/z_db/protocol" }
zutil_db = { path = "../db" }
json_parsing = { path = "../json_parsing" }
ui_math = { path = "../ui_math" }
logging = { path = "../logging" }
fading_popup = { path = "/home/zakke/ProgStuff/egui/reusable_components/fading_popup" }
popup = { path = "/home/zakke/ProgStuff/egui/reusable_components/popup" }
error_stuff = { path = "../error_stuff" }
design = { path = "../design" }
db_wrapper = { path = "/home/zakke/ProgStuff/z_db/db_wrapper", default-features = false, features = ["native"] }

[lints]
workspace = true
