[package]
name = "zutil_db"
version.workspace = true
edition.workspace = true

[dependencies]
protocol = { path = "/home/zakke/ProgStuff/z_db/protocol" }
db_wrapper = { path = "/home/zakke/ProgStuff/z_db/db_wrapper", default-features = false, features = ["native"] }
json_parsing = { path = "../json_parsing" }

[lints]
workspace = true
